backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: frojo/same-page-website
media_folder: "src/assets/img"
public_folder: "/assets/img"
logo_url: "https://www.samepagefilms.co/assets/img/logo.svg"

media_library:
  name: cloudinary
  config:
    cloud_name: dyewnjw4e
    api_key: 351867428198551

preview: false

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Portfolio Order"
    name: "portfolio_order"
    files: 
      - label: "Portfolio Item Order"
        name: "portfolio_order"
        widget: list
        file: "src/_data/portfolio_order.yaml" 
        fields:
        - label: "Portfolio Item Order"
          name: "order"
          widget: "list"
          fields: 
          - label: Portfolio Item
            name: id 
            widget: "relation"
            collection: "portfolio"
            value_field: "id"
            search_fields: ["my_title"]
            display_fields: ["my_title"]
  - label: "Portfolio Items"
    name: "portfolio"
    folder: "src/_collections/portfolio"
    create: true
    preview: false
    fields:
      - { label: "Title", name: "my_title", widget: "string" }
      - { label: "ID - DO NOT CHANGE", name: "id", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Video Embed", name: "video_embed", widget: "code" }
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields: 
          - label: "Credit"
            name: "credit"
            widget: "object"
            fields:
              - { label: 'Role', name: 'role', widget: 'string' }
              - label: Names
                name: names 
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }

      - label: "Stills"
        name: "stills"
        widget: image
        media_library:
          config:
            multiple: true
  - label: "About Page"
    name: "about"
    files:
      - label: "Front Page"
        name: "front-page"
        file: "src/_data/about/front_page.yaml"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: text
          - label: Image
            name: image
            widget: image
            media_library:
              config:
                multiple: false
      - label: "Services"
        name: "services"
        file: "src/_data/about/services.yaml"
        fields:
          - label: Services 
            name: services
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "BTS Images Collection 1"
        name: "bts1"
        file: "src/_data/about/bts1.yaml"
        fields:
          - label: Photos
            name: photos 
            widget: image
            media_library:
              config:
                multiple: true
          - label: Nicknacks
            name: nicknacks 
            widget: image
            media_library:
              config:
                multiple: true
      - label: "BTS Images Collection 2"
        name: "bts2"
        file: "src/_data/about/bts2.yaml"
        fields:
          - label: Photos
            name: photos 
            widget: image
            media_library:
              config:
                multiple: true
          - label: Nicknacks
            name: nicknacks 
            widget: image
            media_library:
              config:
                multiple: true